//
//Warning: This file was automatically generated by fourier_transform_generate.py
//         Do not edit it!
//

/*

libMeshlessVis
Copyright (C) 2008 Andrew Corrigan

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

*/

#ifndef FOURIER_TRANSFORM_H_
#define FOURIER_TRANSFORM_H_

#include "meshless_vis.h"
#include "meshless.h"

void fourier_transform(MeshlessDataset* meshless_dataset, VisConfig* vis_config);

inline float fourier_transform_sph(float r);
void fourier_transform_sph_half_domain_first_group(Group group, VisConfig vis_config);
void fourier_transform_sph_half_domain_first_group_no_radii(Group group, VisConfig vis_config);
void fourier_transform_sph_half_domain(Group group, VisConfig vis_config);
void fourier_transform_sph_half_domain_no_radii(Group group, VisConfig vis_config);

inline float fourier_transform_gaussian(float r);
void fourier_transform_gaussian_half_domain_first_group(Group group, VisConfig vis_config);
void fourier_transform_gaussian_half_domain_first_group_no_radii(Group group, VisConfig vis_config);
void fourier_transform_gaussian_half_domain(Group group, VisConfig vis_config);
void fourier_transform_gaussian_half_domain_no_radii(Group group, VisConfig vis_config);

inline float fourier_transform_wendland_d3_c2(float r);
void fourier_transform_wendland_d3_c2_half_domain_first_group(Group group, VisConfig vis_config);
void fourier_transform_wendland_d3_c2_half_domain_first_group_no_radii(Group group, VisConfig vis_config);
void fourier_transform_wendland_d3_c2_half_domain(Group group, VisConfig vis_config);
void fourier_transform_wendland_d3_c2_half_domain_no_radii(Group group, VisConfig vis_config);


#endif /*FOURIER_TRANSFORM_H_*/
